# Generated by Django 4.1.1 on 2022-10-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='product_year',
        ),
    ]
