# Generated by Django 4.1.1 on 2022-10-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_product_product_interior2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
