# Generated by Django 4.1.1 on 2022-10-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_subscribedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subscribedusers',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
